
title = "Home"
baseURL = "https://viggy28.dev"
languageCode = "en-us"
theme = "ananke"
#themesDir = "../.."
disqusShortname = "viggy28-dev"

MetaDataFormat = "yaml"
DefaultContentLanguage = "en"
SectionPagesMenu = "main"
Paginate = 5 # this is set low for demonstrating with dummy content. Set to a higher number
googleAnalytics = "UA-75733246-2"
enableRobotsTXT = true
HUGO_ENV="production"

[sitemap]
  changefreq = "monthly"
  priority = 0.5
  filename = "sitemap.xml"

[params]
  favicon = ""
  description = "The last theme you'll ever need. Maybe."
  facebook = ""
  twitter = "https://twitter.com/viggy28"
  instagram = ""
  youtube = ""
  github = "https://github.com/viggy28"
  gitlab = "https://gitlab.com/viggy28"
  linkedin = "https://www.linkedin.com/in/vigneshravichandran28/"
  mastodon = ""
  # choose a background color from any on this page: http://tachyons.io/docs/themes/skins/ and preface it with "bg-"
  background_color_class = "bg-black"
  featured_image = "/images/gohugo-default-sample-hero-image.jpg"
  recent_posts_number = 5