stages:
  - build-push-docker
  - deploy-new-service

variables:
    projectid: "replace-your-project-id"
    service: "cloudrun-cicd"
    region: "us-central1"
    image_name: "cloudrun-cicd"

build-push-docker-job:
  stage: build-push-docker
  image: docker:latest
  services:
    - docker:dind
  before_script:
    - echo $CLOUDRUN_CICD_SA_KEY > ${HOME}/service_key.json
    - cat ${HOME}/service_key.json | docker login -u _json_key --password-stdin https://gcr.io
  script:
    - docker build -t gcr.io/$projectid/$image_name:latest .
    - docker push gcr.io/$projectid/$image_name:latest

deploy-new-service-job:
  stage: deploy-new-service
  before_script:
    # Download and install Google Cloud SDK. Source it so you can use it from any where
    - mkdir /software
    - cd /software
    - wget https://dl.google.com/dl/cloudsdk/release/google-cloud-sdk.tar.gz
    - tar zxvf google-cloud-sdk.tar.gz && ./google-cloud-sdk/install.sh --usage-reporting=false --path-update=true
    - source /root/.bashrc
    - gcloud components install beta
    # Write our GCP service account private key into a file
    - echo $CLOUDRUN_CICD_SA_KEY > ${HOME}/service_key.json
  script:
    - gcloud auth activate-service-account --key-file ${HOME}/service_key.json
    - gcloud beta run deploy $service --region $region --project $projectid --image gcr.io/$projectid/$image_name:latest
    - gcloud beta run services add-iam-policy-binding $service --project $projectid --member="allUsers" --role="roles/run.invoker" --region $region