version: "3"
 
services:
 database0:
   image: jgiannuzzi/postgres-bdr
   restart: always
   ports:
     - 54325:5432
   volumes:
     - /Users/viggy28/tech/docker/volumes/postgres0:/var/lib/postgresql/data
   environment:
     POSTGRES_PASSWORD: "replace with your password"
     TCP_PORTS: "5432"

 database1:
   image: jgiannuzzi/postgres-bdr
   restart: always
   ports:
     - 54326:5432
   volumes:
     - /Users/viggy28/tech/docker/volumes/postgres1:/var/lib/postgresql/data
   environment:
     POSTGRES_PASSWORD: "replace with your password"
     TCP_PORTS: "5432"

 proxy:
   image: dockercloud/haproxy 
   links:
     - database0
     - database1
   volumes:
     - /var/run/docker.sock:/var/run/docker.sock
   ports:
     - "15432:5432"
   container_name: postgres-haproxy
 
 pool:
   image: edoburu/pgbouncer
   ports:
     - "5432:5432"
   environment:
    DB_USER: "postgres"
    DB_PASSWORD: "replace with your password"
    DB_HOST: "postgres-haproxy"
    DB_NAME: "bdrdemo"
    DB_PORT: "5432"