name: deploy

on: 
  push:
    branches: [ master ]

jobs:
  build:
    runs-on: ubuntu-latest
    container: vira28/hugo-firebase:1.0
    steps:
      - uses: actions/checkout@v2

      - name: set environment variable
        run: HUGO_ENV=production hugo

      - name: deploy to firebase
        run: firebase --token ${{ secrets.FIREBASE_TOKEN }} --project ${{ secrets.PROD_GCP_PROJECTID }} deploy